# Docker Compose配置文件
# 用于同时运行多个学生项目

version: '3.8'

services:
  # 主展示平台
  main-platform:
    build: .
    container_name: db-sys-platform
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - db-sys-network

  # 示例学生项目1 - 图书管理系统
  # student1-project:
  #   image: student1/library-system:latest
  #   container_name: library-system
  #   ports:
  #     - "5001:5000"
  #   networks:
  #     - db-sys-network

  # 示例学生项目2 - 在线商城
  # student2-project:
  #   image: student2/shop-system:latest
  #   container_name: shop-system
  #   ports:
  #     - "5002:5000"
  #   networks:
  #     - db-sys-network

networks:
  db-sys-network:
    driver: bridge
